"""

Revision ID: 1bc7e00a3989
Revises: e62f10782e65
Create Date: 2025-03-14 03:53:22.430691

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1bc7e00a3989"
down_revision = "e62f10782e65"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "IN_PROGRESS", "COMPLETED", "CANCELED", name="orderstatusenum"
        ),
        nullable=False,
        default="PENDING",
    )
    op.alter_column(
        "order",
        "source",
        existing_type=postgresql.ENUM(
            "EMAIL", "PHONE", "WEBSITE", "MOBILE_APP", "OTHER", name="ordersourceenum"
        ),
        nullable=False,
        default="EMAIL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order",
        "source",
        existing_type=postgresql.ENUM(
            "EMAIL", "PHONE", "WEBSITE", "MOBILE_APP", "OTHER", name="ordersourceenum"
        ),
        nullable=True,
    )
    op.alter_column(
        "order",
        "status",
        existing_type=postgresql.ENUM(
            "PENDING", "IN_PROGRESS", "COMPLETED", "CANCELED", name="orderstatusenum"
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
