"""

Revision ID: e62f10782e65
Revises:
Create Date: 2025-03-13 04:19:32.359382

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e62f10782e65"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("to", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("reply_to", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("customer_name", sa.String(length=255), nullable=False),
        sa.Column("email_id", sa.BigInteger(), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("service_requested", sa.Text(), nullable=False),
        sa.Column("order_details", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", "CANCELED", name="orderstatusenum"),
            nullable=True,
        ),
        sa.Column("assigned_to", sa.String(length=255), nullable=True),
        sa.Column(
            "source",
            sa.Enum("EMAIL", "PHONE", "WEBSITE", "MOBILE_APP", "OTHER", name="ordersourceenum"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["email_id"], ["email.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order")
    op.drop_table("email")
    # ### end Alembic commands ###
