services:

  app:
    image: ${REGISTRY}/${IMAGE_NAME}:${TAG}
    command:
      - /bin/sh
      - -e
      - -c
      - |
        alembic upgrade head
        gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --access-logfile -
