services:
    app:
        command:
            - /bin/sh
            - -e
            - -c
            - |
                alembic upgrade head
                gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --access-logfile -
        env_file: .env
        ports:
            - ${HOST_APP_PORT}:8000
        restart: always

    db:
        image: postgres:15
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - ${HOST_DB_PORT}:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
            interval: 2s
            timeout: 30s
            retries: 10
        command:
            - "postgres"
            - "-c"
            - "wal_level=logical"
            - "-c"
            - "max_wal_senders=10"
            - "-c"
            - "max_replication_slots=10"

volumes:
    postgres-data:
